// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package producer

import (
	"context"
	"github.com/redis/go-redis/v9"
	"sync"
)

// Ensure, that RedisMock does implement Redis.
// If this is not the case, regenerate this file with moq.
var _ Redis = &RedisMock{}

// RedisMock is a mock implementation of Redis.
//
//	func TestSomethingThatUsesRedis(t *testing.T) {
//
//		// make and configure a mocked Redis
//		mockedRedis := &RedisMock{
//			TxPipelinedFunc: func(ctx context.Context, fn func(redis.Pipeliner) error) ([]redis.Cmder, error) {
//				panic("mock out the TxPipelined method")
//			},
//			XAddFunc: func(ctx context.Context, args *redis.XAddArgs) *redis.StringCmd {
//				panic("mock out the XAdd method")
//			},
//		}
//
//		// use mockedRedis in code that requires Redis
//		// and then make assertions.
//
//	}
type RedisMock struct {
	// TxPipelinedFunc mocks the TxPipelined method.
	TxPipelinedFunc func(ctx context.Context, fn func(redis.Pipeliner) error) ([]redis.Cmder, error)

	// XAddFunc mocks the XAdd method.
	XAddFunc func(ctx context.Context, args *redis.XAddArgs) *redis.StringCmd

	// calls tracks calls to the methods.
	calls struct {
		// TxPipelined holds details about calls to the TxPipelined method.
		TxPipelined []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Fn is the fn argument value.
			Fn func(redis.Pipeliner) error
		}
		// XAdd holds details about calls to the XAdd method.
		XAdd []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Args is the args argument value.
			Args *redis.XAddArgs
		}
	}
	lockTxPipelined sync.RWMutex
	lockXAdd        sync.RWMutex
}

// TxPipelined calls TxPipelinedFunc.
func (mock *RedisMock) TxPipelined(ctx context.Context, fn func(redis.Pipeliner) error) ([]redis.Cmder, error) {
	if mock.TxPipelinedFunc == nil {
		panic("RedisMock.TxPipelinedFunc: method is nil but Redis.TxPipelined was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Fn  func(redis.Pipeliner) error
	}{
		Ctx: ctx,
		Fn:  fn,
	}
	mock.lockTxPipelined.Lock()
	mock.calls.TxPipelined = append(mock.calls.TxPipelined, callInfo)
	mock.lockTxPipelined.Unlock()
	return mock.TxPipelinedFunc(ctx, fn)
}

// TxPipelinedCalls gets all the calls that were made to TxPipelined.
// Check the length with:
//
//	len(mockedRedis.TxPipelinedCalls())
func (mock *RedisMock) TxPipelinedCalls() []struct {
	Ctx context.Context
	Fn  func(redis.Pipeliner) error
} {
	var calls []struct {
		Ctx context.Context
		Fn  func(redis.Pipeliner) error
	}
	mock.lockTxPipelined.RLock()
	calls = mock.calls.TxPipelined
	mock.lockTxPipelined.RUnlock()
	return calls
}

// XAdd calls XAddFunc.
func (mock *RedisMock) XAdd(ctx context.Context, args *redis.XAddArgs) *redis.StringCmd {
	if mock.XAddFunc == nil {
		panic("RedisMock.XAddFunc: method is nil but Redis.XAdd was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Args *redis.XAddArgs
	}{
		Ctx:  ctx,
		Args: args,
	}
	mock.lockXAdd.Lock()
	mock.calls.XAdd = append(mock.calls.XAdd, callInfo)
	mock.lockXAdd.Unlock()
	return mock.XAddFunc(ctx, args)
}

// XAddCalls gets all the calls that were made to XAdd.
// Check the length with:
//
//	len(mockedRedis.XAddCalls())
func (mock *RedisMock) XAddCalls() []struct {
	Ctx  context.Context
	Args *redis.XAddArgs
} {
	var calls []struct {
		Ctx  context.Context
		Args *redis.XAddArgs
	}
	mock.lockXAdd.RLock()
	calls = mock.calls.XAdd
	mock.lockXAdd.RUnlock()
	return calls
}
