// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package delayqueue

import (
	"context"
	"github.com/redis/go-redis/v9"
	"sync"
)

// Ensure, that RedisMock does implement Redis.
// If this is not the case, regenerate this file with moq.
var _ Redis = &RedisMock{}

// RedisMock is a mock implementation of Redis.
//
//	func TestSomethingThatUsesRedis(t *testing.T) {
//
//		// make and configure a mocked Redis
//		mockedRedis := &RedisMock{
//			KeysFunc: func(ctx context.Context, pattern string) *redis.StringSliceCmd {
//				panic("mock out the Keys method")
//			},
//			ZAddFunc: func(ctx context.Context, key string, members ...redis.Z) *redis.IntCmd {
//				panic("mock out the ZAdd method")
//			},
//			ZRangeByScoreFunc: func(ctx context.Context, key string, opt *redis.ZRangeBy) *redis.StringSliceCmd {
//				panic("mock out the ZRangeByScore method")
//			},
//			ZRemFunc: func(ctx context.Context, key string, members ...any) *redis.IntCmd {
//				panic("mock out the ZRem method")
//			},
//		}
//
//		// use mockedRedis in code that requires Redis
//		// and then make assertions.
//
//	}
type RedisMock struct {
	// KeysFunc mocks the Keys method.
	KeysFunc func(ctx context.Context, pattern string) *redis.StringSliceCmd

	// ZAddFunc mocks the ZAdd method.
	ZAddFunc func(ctx context.Context, key string, members ...redis.Z) *redis.IntCmd

	// ZRangeByScoreFunc mocks the ZRangeByScore method.
	ZRangeByScoreFunc func(ctx context.Context, key string, opt *redis.ZRangeBy) *redis.StringSliceCmd

	// ZRemFunc mocks the ZRem method.
	ZRemFunc func(ctx context.Context, key string, members ...any) *redis.IntCmd

	// calls tracks calls to the methods.
	calls struct {
		// Keys holds details about calls to the Keys method.
		Keys []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Pattern is the pattern argument value.
			Pattern string
		}
		// ZAdd holds details about calls to the ZAdd method.
		ZAdd []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Key is the key argument value.
			Key string
			// Members is the members argument value.
			Members []redis.Z
		}
		// ZRangeByScore holds details about calls to the ZRangeByScore method.
		ZRangeByScore []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Key is the key argument value.
			Key string
			// Opt is the opt argument value.
			Opt *redis.ZRangeBy
		}
		// ZRem holds details about calls to the ZRem method.
		ZRem []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Key is the key argument value.
			Key string
			// Members is the members argument value.
			Members []any
		}
	}
	lockKeys          sync.RWMutex
	lockZAdd          sync.RWMutex
	lockZRangeByScore sync.RWMutex
	lockZRem          sync.RWMutex
}

// Keys calls KeysFunc.
func (mock *RedisMock) Keys(ctx context.Context, pattern string) *redis.StringSliceCmd {
	if mock.KeysFunc == nil {
		panic("RedisMock.KeysFunc: method is nil but Redis.Keys was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		Pattern string
	}{
		Ctx:     ctx,
		Pattern: pattern,
	}
	mock.lockKeys.Lock()
	mock.calls.Keys = append(mock.calls.Keys, callInfo)
	mock.lockKeys.Unlock()
	return mock.KeysFunc(ctx, pattern)
}

// KeysCalls gets all the calls that were made to Keys.
// Check the length with:
//
//	len(mockedRedis.KeysCalls())
func (mock *RedisMock) KeysCalls() []struct {
	Ctx     context.Context
	Pattern string
} {
	var calls []struct {
		Ctx     context.Context
		Pattern string
	}
	mock.lockKeys.RLock()
	calls = mock.calls.Keys
	mock.lockKeys.RUnlock()
	return calls
}

// ZAdd calls ZAddFunc.
func (mock *RedisMock) ZAdd(ctx context.Context, key string, members ...redis.Z) *redis.IntCmd {
	if mock.ZAddFunc == nil {
		panic("RedisMock.ZAddFunc: method is nil but Redis.ZAdd was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		Key     string
		Members []redis.Z
	}{
		Ctx:     ctx,
		Key:     key,
		Members: members,
	}
	mock.lockZAdd.Lock()
	mock.calls.ZAdd = append(mock.calls.ZAdd, callInfo)
	mock.lockZAdd.Unlock()
	return mock.ZAddFunc(ctx, key, members...)
}

// ZAddCalls gets all the calls that were made to ZAdd.
// Check the length with:
//
//	len(mockedRedis.ZAddCalls())
func (mock *RedisMock) ZAddCalls() []struct {
	Ctx     context.Context
	Key     string
	Members []redis.Z
} {
	var calls []struct {
		Ctx     context.Context
		Key     string
		Members []redis.Z
	}
	mock.lockZAdd.RLock()
	calls = mock.calls.ZAdd
	mock.lockZAdd.RUnlock()
	return calls
}

// ZRangeByScore calls ZRangeByScoreFunc.
func (mock *RedisMock) ZRangeByScore(ctx context.Context, key string, opt *redis.ZRangeBy) *redis.StringSliceCmd {
	if mock.ZRangeByScoreFunc == nil {
		panic("RedisMock.ZRangeByScoreFunc: method is nil but Redis.ZRangeByScore was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Key string
		Opt *redis.ZRangeBy
	}{
		Ctx: ctx,
		Key: key,
		Opt: opt,
	}
	mock.lockZRangeByScore.Lock()
	mock.calls.ZRangeByScore = append(mock.calls.ZRangeByScore, callInfo)
	mock.lockZRangeByScore.Unlock()
	return mock.ZRangeByScoreFunc(ctx, key, opt)
}

// ZRangeByScoreCalls gets all the calls that were made to ZRangeByScore.
// Check the length with:
//
//	len(mockedRedis.ZRangeByScoreCalls())
func (mock *RedisMock) ZRangeByScoreCalls() []struct {
	Ctx context.Context
	Key string
	Opt *redis.ZRangeBy
} {
	var calls []struct {
		Ctx context.Context
		Key string
		Opt *redis.ZRangeBy
	}
	mock.lockZRangeByScore.RLock()
	calls = mock.calls.ZRangeByScore
	mock.lockZRangeByScore.RUnlock()
	return calls
}

// ZRem calls ZRemFunc.
func (mock *RedisMock) ZRem(ctx context.Context, key string, members ...any) *redis.IntCmd {
	if mock.ZRemFunc == nil {
		panic("RedisMock.ZRemFunc: method is nil but Redis.ZRem was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		Key     string
		Members []any
	}{
		Ctx:     ctx,
		Key:     key,
		Members: members,
	}
	mock.lockZRem.Lock()
	mock.calls.ZRem = append(mock.calls.ZRem, callInfo)
	mock.lockZRem.Unlock()
	return mock.ZRemFunc(ctx, key, members...)
}

// ZRemCalls gets all the calls that were made to ZRem.
// Check the length with:
//
//	len(mockedRedis.ZRemCalls())
func (mock *RedisMock) ZRemCalls() []struct {
	Ctx     context.Context
	Key     string
	Members []any
} {
	var calls []struct {
		Ctx     context.Context
		Key     string
		Members []any
	}
	mock.lockZRem.RLock()
	calls = mock.calls.ZRem
	mock.lockZRem.RUnlock()
	return calls
}
