// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package delayqueue

import (
	"context"
	"github.com/Orfeo42/go-redismq/v3/internal/mqtype"
	"sync"
)

// Ensure, that TracerMock does implement Tracer.
// If this is not the case, regenerate this file with moq.
var _ Tracer = &TracerMock{}

// TracerMock is a mock implementation of Tracer.
//
//	func TestSomethingThatUsesTracer(t *testing.T) {
//
//		// make and configure a mocked Tracer
//		mockedTracer := &TracerMock{
//			StampTraceIDFunc: func(ctx context.Context, message *mqtype.Message)  {
//				panic("mock out the StampTraceID method")
//			},
//		}
//
//		// use mockedTracer in code that requires Tracer
//		// and then make assertions.
//
//	}
type TracerMock struct {
	// StampTraceIDFunc mocks the StampTraceID method.
	StampTraceIDFunc func(ctx context.Context, message *mqtype.Message)

	// calls tracks calls to the methods.
	calls struct {
		// StampTraceID holds details about calls to the StampTraceID method.
		StampTraceID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Message is the message argument value.
			Message *mqtype.Message
		}
	}
	lockStampTraceID sync.RWMutex
}

// StampTraceID calls StampTraceIDFunc.
func (mock *TracerMock) StampTraceID(ctx context.Context, message *mqtype.Message) {
	if mock.StampTraceIDFunc == nil {
		panic("TracerMock.StampTraceIDFunc: method is nil but Tracer.StampTraceID was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		Message *mqtype.Message
	}{
		Ctx:     ctx,
		Message: message,
	}
	mock.lockStampTraceID.Lock()
	mock.calls.StampTraceID = append(mock.calls.StampTraceID, callInfo)
	mock.lockStampTraceID.Unlock()
	mock.StampTraceIDFunc(ctx, message)
}

// StampTraceIDCalls gets all the calls that were made to StampTraceID.
// Check the length with:
//
//	len(mockedTracer.StampTraceIDCalls())
func (mock *TracerMock) StampTraceIDCalls() []struct {
	Ctx     context.Context
	Message *mqtype.Message
} {
	var calls []struct {
		Ctx     context.Context
		Message *mqtype.Message
	}
	mock.lockStampTraceID.RLock()
	calls = mock.calls.StampTraceID
	mock.lockStampTraceID.RUnlock()
	return calls
}
