// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package consumer

import (
	"context"
	"github.com/Orfeo42/go-redismq/v3/internal/mqtype"
	"sync"
)

// Ensure, that DelaySchedulerMock does implement DelayScheduler.
// If this is not the case, regenerate this file with moq.
var _ DelayScheduler = &DelaySchedulerMock{}

// DelaySchedulerMock is a mock implementation of DelayScheduler.
//
//	func TestSomethingThatUsesDelayScheduler(t *testing.T) {
//
//		// make and configure a mocked DelayScheduler
//		mockedDelayScheduler := &DelaySchedulerMock{
//			ScheduleDelayFunc: func(ctx context.Context, message *mqtype.Message, delaySeconds int64) (bool, error) {
//				panic("mock out the ScheduleDelay method")
//			},
//		}
//
//		// use mockedDelayScheduler in code that requires DelayScheduler
//		// and then make assertions.
//
//	}
type DelaySchedulerMock struct {
	// ScheduleDelayFunc mocks the ScheduleDelay method.
	ScheduleDelayFunc func(ctx context.Context, message *mqtype.Message, delaySeconds int64) (bool, error)

	// calls tracks calls to the methods.
	calls struct {
		// ScheduleDelay holds details about calls to the ScheduleDelay method.
		ScheduleDelay []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Message is the message argument value.
			Message *mqtype.Message
			// DelaySeconds is the delaySeconds argument value.
			DelaySeconds int64
		}
	}
	lockScheduleDelay sync.RWMutex
}

// ScheduleDelay calls ScheduleDelayFunc.
func (mock *DelaySchedulerMock) ScheduleDelay(ctx context.Context, message *mqtype.Message, delaySeconds int64) (bool, error) {
	if mock.ScheduleDelayFunc == nil {
		panic("DelaySchedulerMock.ScheduleDelayFunc: method is nil but DelayScheduler.ScheduleDelay was just called")
	}
	callInfo := struct {
		Ctx          context.Context
		Message      *mqtype.Message
		DelaySeconds int64
	}{
		Ctx:          ctx,
		Message:      message,
		DelaySeconds: delaySeconds,
	}
	mock.lockScheduleDelay.Lock()
	mock.calls.ScheduleDelay = append(mock.calls.ScheduleDelay, callInfo)
	mock.lockScheduleDelay.Unlock()
	return mock.ScheduleDelayFunc(ctx, message, delaySeconds)
}

// ScheduleDelayCalls gets all the calls that were made to ScheduleDelay.
// Check the length with:
//
//	len(mockedDelayScheduler.ScheduleDelayCalls())
func (mock *DelaySchedulerMock) ScheduleDelayCalls() []struct {
	Ctx          context.Context
	Message      *mqtype.Message
	DelaySeconds int64
} {
	var calls []struct {
		Ctx          context.Context
		Message      *mqtype.Message
		DelaySeconds int64
	}
	mock.lockScheduleDelay.RLock()
	calls = mock.calls.ScheduleDelay
	mock.lockScheduleDelay.RUnlock()
	return calls
}
