// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package consumer

import (
	"github.com/Orfeo42/go-redismq/v3/internal/mqtype"
	"sync"
)

// Ensure, that ListenerRegistryMock does implement ListenerRegistry.
// If this is not the case, regenerate this file with moq.
var _ ListenerRegistry = &ListenerRegistryMock{}

// ListenerRegistryMock is a mock implementation of ListenerRegistry.
//
//	func TestSomethingThatUsesListenerRegistry(t *testing.T) {
//
//		// make and configure a mocked ListenerRegistry
//		mockedListenerRegistry := &ListenerRegistryMock{
//			GetListenerForFunc: func(topic string, tag string) mqtype.IMessageListener {
//				panic("mock out the GetListenerFor method")
//			},
//			GetTopicsFunc: func() []string {
//				panic("mock out the GetTopics method")
//			},
//			TopicCountFunc: func() int {
//				panic("mock out the TopicCount method")
//			},
//		}
//
//		// use mockedListenerRegistry in code that requires ListenerRegistry
//		// and then make assertions.
//
//	}
type ListenerRegistryMock struct {
	// GetListenerForFunc mocks the GetListenerFor method.
	GetListenerForFunc func(topic string, tag string) mqtype.IMessageListener

	// GetTopicsFunc mocks the GetTopics method.
	GetTopicsFunc func() []string

	// TopicCountFunc mocks the TopicCount method.
	TopicCountFunc func() int

	// calls tracks calls to the methods.
	calls struct {
		// GetListenerFor holds details about calls to the GetListenerFor method.
		GetListenerFor []struct {
			// Topic is the topic argument value.
			Topic string
			// Tag is the tag argument value.
			Tag string
		}
		// GetTopics holds details about calls to the GetTopics method.
		GetTopics []struct {
		}
		// TopicCount holds details about calls to the TopicCount method.
		TopicCount []struct {
		}
	}
	lockGetListenerFor sync.RWMutex
	lockGetTopics      sync.RWMutex
	lockTopicCount     sync.RWMutex
}

// GetListenerFor calls GetListenerForFunc.
func (mock *ListenerRegistryMock) GetListenerFor(topic string, tag string) mqtype.IMessageListener {
	if mock.GetListenerForFunc == nil {
		panic("ListenerRegistryMock.GetListenerForFunc: method is nil but ListenerRegistry.GetListenerFor was just called")
	}
	callInfo := struct {
		Topic string
		Tag   string
	}{
		Topic: topic,
		Tag:   tag,
	}
	mock.lockGetListenerFor.Lock()
	mock.calls.GetListenerFor = append(mock.calls.GetListenerFor, callInfo)
	mock.lockGetListenerFor.Unlock()
	return mock.GetListenerForFunc(topic, tag)
}

// GetListenerForCalls gets all the calls that were made to GetListenerFor.
// Check the length with:
//
//	len(mockedListenerRegistry.GetListenerForCalls())
func (mock *ListenerRegistryMock) GetListenerForCalls() []struct {
	Topic string
	Tag   string
} {
	var calls []struct {
		Topic string
		Tag   string
	}
	mock.lockGetListenerFor.RLock()
	calls = mock.calls.GetListenerFor
	mock.lockGetListenerFor.RUnlock()
	return calls
}

// GetTopics calls GetTopicsFunc.
func (mock *ListenerRegistryMock) GetTopics() []string {
	if mock.GetTopicsFunc == nil {
		panic("ListenerRegistryMock.GetTopicsFunc: method is nil but ListenerRegistry.GetTopics was just called")
	}
	callInfo := struct {
	}{}
	mock.lockGetTopics.Lock()
	mock.calls.GetTopics = append(mock.calls.GetTopics, callInfo)
	mock.lockGetTopics.Unlock()
	return mock.GetTopicsFunc()
}

// GetTopicsCalls gets all the calls that were made to GetTopics.
// Check the length with:
//
//	len(mockedListenerRegistry.GetTopicsCalls())
func (mock *ListenerRegistryMock) GetTopicsCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockGetTopics.RLock()
	calls = mock.calls.GetTopics
	mock.lockGetTopics.RUnlock()
	return calls
}

// TopicCount calls TopicCountFunc.
func (mock *ListenerRegistryMock) TopicCount() int {
	if mock.TopicCountFunc == nil {
		panic("ListenerRegistryMock.TopicCountFunc: method is nil but ListenerRegistry.TopicCount was just called")
	}
	callInfo := struct {
	}{}
	mock.lockTopicCount.Lock()
	mock.calls.TopicCount = append(mock.calls.TopicCount, callInfo)
	mock.lockTopicCount.Unlock()
	return mock.TopicCountFunc()
}

// TopicCountCalls gets all the calls that were made to TopicCount.
// Check the length with:
//
//	len(mockedListenerRegistry.TopicCountCalls())
func (mock *ListenerRegistryMock) TopicCountCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockTopicCount.RLock()
	calls = mock.calls.TopicCount
	mock.lockTopicCount.RUnlock()
	return calls
}
