// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package consumer

import (
	"context"
	"github.com/redis/go-redis/v9"
	"sync"
)

// Ensure, that RedisMock does implement Redis.
// If this is not the case, regenerate this file with moq.
var _ Redis = &RedisMock{}

// RedisMock is a mock implementation of Redis.
//
//	func TestSomethingThatUsesRedis(t *testing.T) {
//
//		// make and configure a mocked Redis
//		mockedRedis := &RedisMock{
//			XAckFunc: func(ctx context.Context, stream string, group string, ids ...string) *redis.IntCmd {
//				panic("mock out the XAck method")
//			},
//			XAddFunc: func(ctx context.Context, args *redis.XAddArgs) *redis.StringCmd {
//				panic("mock out the XAdd method")
//			},
//			XGroupCreateConsumerFunc: func(ctx context.Context, stream string, group string, consumer string) *redis.IntCmd {
//				panic("mock out the XGroupCreateConsumer method")
//			},
//			XGroupCreateMkStreamFunc: func(ctx context.Context, stream string, group string, start string) *redis.StatusCmd {
//				panic("mock out the XGroupCreateMkStream method")
//			},
//			XInfoGroupsFunc: func(ctx context.Context, key string) *redis.XInfoGroupsCmd {
//				panic("mock out the XInfoGroups method")
//			},
//			XReadGroupFunc: func(ctx context.Context, a *redis.XReadGroupArgs) *redis.XStreamSliceCmd {
//				panic("mock out the XReadGroup method")
//			},
//			XTrimMaxLenFunc: func(ctx context.Context, key string, maxLen int64) *redis.IntCmd {
//				panic("mock out the XTrimMaxLen method")
//			},
//		}
//
//		// use mockedRedis in code that requires Redis
//		// and then make assertions.
//
//	}
type RedisMock struct {
	// XAckFunc mocks the XAck method.
	XAckFunc func(ctx context.Context, stream string, group string, ids ...string) *redis.IntCmd

	// XAddFunc mocks the XAdd method.
	XAddFunc func(ctx context.Context, args *redis.XAddArgs) *redis.StringCmd

	// XGroupCreateConsumerFunc mocks the XGroupCreateConsumer method.
	XGroupCreateConsumerFunc func(ctx context.Context, stream string, group string, consumer string) *redis.IntCmd

	// XGroupCreateMkStreamFunc mocks the XGroupCreateMkStream method.
	XGroupCreateMkStreamFunc func(ctx context.Context, stream string, group string, start string) *redis.StatusCmd

	// XInfoGroupsFunc mocks the XInfoGroups method.
	XInfoGroupsFunc func(ctx context.Context, key string) *redis.XInfoGroupsCmd

	// XReadGroupFunc mocks the XReadGroup method.
	XReadGroupFunc func(ctx context.Context, a *redis.XReadGroupArgs) *redis.XStreamSliceCmd

	// XTrimMaxLenFunc mocks the XTrimMaxLen method.
	XTrimMaxLenFunc func(ctx context.Context, key string, maxLen int64) *redis.IntCmd

	// calls tracks calls to the methods.
	calls struct {
		// XAck holds details about calls to the XAck method.
		XAck []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Stream is the stream argument value.
			Stream string
			// Group is the group argument value.
			Group string
			// Ids is the ids argument value.
			Ids []string
		}
		// XAdd holds details about calls to the XAdd method.
		XAdd []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Args is the args argument value.
			Args *redis.XAddArgs
		}
		// XGroupCreateConsumer holds details about calls to the XGroupCreateConsumer method.
		XGroupCreateConsumer []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Stream is the stream argument value.
			Stream string
			// Group is the group argument value.
			Group string
			// Consumer is the consumer argument value.
			Consumer string
		}
		// XGroupCreateMkStream holds details about calls to the XGroupCreateMkStream method.
		XGroupCreateMkStream []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Stream is the stream argument value.
			Stream string
			// Group is the group argument value.
			Group string
			// Start is the start argument value.
			Start string
		}
		// XInfoGroups holds details about calls to the XInfoGroups method.
		XInfoGroups []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Key is the key argument value.
			Key string
		}
		// XReadGroup holds details about calls to the XReadGroup method.
		XReadGroup []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// A is the a argument value.
			A *redis.XReadGroupArgs
		}
		// XTrimMaxLen holds details about calls to the XTrimMaxLen method.
		XTrimMaxLen []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Key is the key argument value.
			Key string
			// MaxLen is the maxLen argument value.
			MaxLen int64
		}
	}
	lockXAck                 sync.RWMutex
	lockXAdd                 sync.RWMutex
	lockXGroupCreateConsumer sync.RWMutex
	lockXGroupCreateMkStream sync.RWMutex
	lockXInfoGroups          sync.RWMutex
	lockXReadGroup           sync.RWMutex
	lockXTrimMaxLen          sync.RWMutex
}

// XAck calls XAckFunc.
func (mock *RedisMock) XAck(ctx context.Context, stream string, group string, ids ...string) *redis.IntCmd {
	if mock.XAckFunc == nil {
		panic("RedisMock.XAckFunc: method is nil but Redis.XAck was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Stream string
		Group  string
		Ids    []string
	}{
		Ctx:    ctx,
		Stream: stream,
		Group:  group,
		Ids:    ids,
	}
	mock.lockXAck.Lock()
	mock.calls.XAck = append(mock.calls.XAck, callInfo)
	mock.lockXAck.Unlock()
	return mock.XAckFunc(ctx, stream, group, ids...)
}

// XAckCalls gets all the calls that were made to XAck.
// Check the length with:
//
//	len(mockedRedis.XAckCalls())
func (mock *RedisMock) XAckCalls() []struct {
	Ctx    context.Context
	Stream string
	Group  string
	Ids    []string
} {
	var calls []struct {
		Ctx    context.Context
		Stream string
		Group  string
		Ids    []string
	}
	mock.lockXAck.RLock()
	calls = mock.calls.XAck
	mock.lockXAck.RUnlock()
	return calls
}

// XAdd calls XAddFunc.
func (mock *RedisMock) XAdd(ctx context.Context, args *redis.XAddArgs) *redis.StringCmd {
	if mock.XAddFunc == nil {
		panic("RedisMock.XAddFunc: method is nil but Redis.XAdd was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Args *redis.XAddArgs
	}{
		Ctx:  ctx,
		Args: args,
	}
	mock.lockXAdd.Lock()
	mock.calls.XAdd = append(mock.calls.XAdd, callInfo)
	mock.lockXAdd.Unlock()
	return mock.XAddFunc(ctx, args)
}

// XAddCalls gets all the calls that were made to XAdd.
// Check the length with:
//
//	len(mockedRedis.XAddCalls())
func (mock *RedisMock) XAddCalls() []struct {
	Ctx  context.Context
	Args *redis.XAddArgs
} {
	var calls []struct {
		Ctx  context.Context
		Args *redis.XAddArgs
	}
	mock.lockXAdd.RLock()
	calls = mock.calls.XAdd
	mock.lockXAdd.RUnlock()
	return calls
}

// XGroupCreateConsumer calls XGroupCreateConsumerFunc.
func (mock *RedisMock) XGroupCreateConsumer(ctx context.Context, stream string, group string, consumer string) *redis.IntCmd {
	if mock.XGroupCreateConsumerFunc == nil {
		panic("RedisMock.XGroupCreateConsumerFunc: method is nil but Redis.XGroupCreateConsumer was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		Stream   string
		Group    string
		Consumer string
	}{
		Ctx:      ctx,
		Stream:   stream,
		Group:    group,
		Consumer: consumer,
	}
	mock.lockXGroupCreateConsumer.Lock()
	mock.calls.XGroupCreateConsumer = append(mock.calls.XGroupCreateConsumer, callInfo)
	mock.lockXGroupCreateConsumer.Unlock()
	return mock.XGroupCreateConsumerFunc(ctx, stream, group, consumer)
}

// XGroupCreateConsumerCalls gets all the calls that were made to XGroupCreateConsumer.
// Check the length with:
//
//	len(mockedRedis.XGroupCreateConsumerCalls())
func (mock *RedisMock) XGroupCreateConsumerCalls() []struct {
	Ctx      context.Context
	Stream   string
	Group    string
	Consumer string
} {
	var calls []struct {
		Ctx      context.Context
		Stream   string
		Group    string
		Consumer string
	}
	mock.lockXGroupCreateConsumer.RLock()
	calls = mock.calls.XGroupCreateConsumer
	mock.lockXGroupCreateConsumer.RUnlock()
	return calls
}

// XGroupCreateMkStream calls XGroupCreateMkStreamFunc.
func (mock *RedisMock) XGroupCreateMkStream(ctx context.Context, stream string, group string, start string) *redis.StatusCmd {
	if mock.XGroupCreateMkStreamFunc == nil {
		panic("RedisMock.XGroupCreateMkStreamFunc: method is nil but Redis.XGroupCreateMkStream was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Stream string
		Group  string
		Start  string
	}{
		Ctx:    ctx,
		Stream: stream,
		Group:  group,
		Start:  start,
	}
	mock.lockXGroupCreateMkStream.Lock()
	mock.calls.XGroupCreateMkStream = append(mock.calls.XGroupCreateMkStream, callInfo)
	mock.lockXGroupCreateMkStream.Unlock()
	return mock.XGroupCreateMkStreamFunc(ctx, stream, group, start)
}

// XGroupCreateMkStreamCalls gets all the calls that were made to XGroupCreateMkStream.
// Check the length with:
//
//	len(mockedRedis.XGroupCreateMkStreamCalls())
func (mock *RedisMock) XGroupCreateMkStreamCalls() []struct {
	Ctx    context.Context
	Stream string
	Group  string
	Start  string
} {
	var calls []struct {
		Ctx    context.Context
		Stream string
		Group  string
		Start  string
	}
	mock.lockXGroupCreateMkStream.RLock()
	calls = mock.calls.XGroupCreateMkStream
	mock.lockXGroupCreateMkStream.RUnlock()
	return calls
}

// XInfoGroups calls XInfoGroupsFunc.
func (mock *RedisMock) XInfoGroups(ctx context.Context, key string) *redis.XInfoGroupsCmd {
	if mock.XInfoGroupsFunc == nil {
		panic("RedisMock.XInfoGroupsFunc: method is nil but Redis.XInfoGroups was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Key string
	}{
		Ctx: ctx,
		Key: key,
	}
	mock.lockXInfoGroups.Lock()
	mock.calls.XInfoGroups = append(mock.calls.XInfoGroups, callInfo)
	mock.lockXInfoGroups.Unlock()
	return mock.XInfoGroupsFunc(ctx, key)
}

// XInfoGroupsCalls gets all the calls that were made to XInfoGroups.
// Check the length with:
//
//	len(mockedRedis.XInfoGroupsCalls())
func (mock *RedisMock) XInfoGroupsCalls() []struct {
	Ctx context.Context
	Key string
} {
	var calls []struct {
		Ctx context.Context
		Key string
	}
	mock.lockXInfoGroups.RLock()
	calls = mock.calls.XInfoGroups
	mock.lockXInfoGroups.RUnlock()
	return calls
}

// XReadGroup calls XReadGroupFunc.
func (mock *RedisMock) XReadGroup(ctx context.Context, a *redis.XReadGroupArgs) *redis.XStreamSliceCmd {
	if mock.XReadGroupFunc == nil {
		panic("RedisMock.XReadGroupFunc: method is nil but Redis.XReadGroup was just called")
	}
	callInfo := struct {
		Ctx context.Context
		A   *redis.XReadGroupArgs
	}{
		Ctx: ctx,
		A:   a,
	}
	mock.lockXReadGroup.Lock()
	mock.calls.XReadGroup = append(mock.calls.XReadGroup, callInfo)
	mock.lockXReadGroup.Unlock()
	return mock.XReadGroupFunc(ctx, a)
}

// XReadGroupCalls gets all the calls that were made to XReadGroup.
// Check the length with:
//
//	len(mockedRedis.XReadGroupCalls())
func (mock *RedisMock) XReadGroupCalls() []struct {
	Ctx context.Context
	A   *redis.XReadGroupArgs
} {
	var calls []struct {
		Ctx context.Context
		A   *redis.XReadGroupArgs
	}
	mock.lockXReadGroup.RLock()
	calls = mock.calls.XReadGroup
	mock.lockXReadGroup.RUnlock()
	return calls
}

// XTrimMaxLen calls XTrimMaxLenFunc.
func (mock *RedisMock) XTrimMaxLen(ctx context.Context, key string, maxLen int64) *redis.IntCmd {
	if mock.XTrimMaxLenFunc == nil {
		panic("RedisMock.XTrimMaxLenFunc: method is nil but Redis.XTrimMaxLen was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Key    string
		MaxLen int64
	}{
		Ctx:    ctx,
		Key:    key,
		MaxLen: maxLen,
	}
	mock.lockXTrimMaxLen.Lock()
	mock.calls.XTrimMaxLen = append(mock.calls.XTrimMaxLen, callInfo)
	mock.lockXTrimMaxLen.Unlock()
	return mock.XTrimMaxLenFunc(ctx, key, maxLen)
}

// XTrimMaxLenCalls gets all the calls that were made to XTrimMaxLen.
// Check the length with:
//
//	len(mockedRedis.XTrimMaxLenCalls())
func (mock *RedisMock) XTrimMaxLenCalls() []struct {
	Ctx    context.Context
	Key    string
	MaxLen int64
} {
	var calls []struct {
		Ctx    context.Context
		Key    string
		MaxLen int64
	}
	mock.lockXTrimMaxLen.RLock()
	calls = mock.calls.XTrimMaxLen
	mock.lockXTrimMaxLen.RUnlock()
	return calls
}
