// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package consumer

import (
	"context"
	"sync"
)

// Ensure, that TransactionCheckerMock does implement TransactionChecker.
// If this is not the case, regenerate this file with moq.
var _ TransactionChecker = &TransactionCheckerMock{}

// TransactionCheckerMock is a mock implementation of TransactionChecker.
//
//	func TestSomethingThatUsesTransactionChecker(t *testing.T) {
//
//		// make and configure a mocked TransactionChecker
//		mockedTransactionChecker := &TransactionCheckerMock{
//			RunFunc: func(ctx context.Context, topic string)  {
//				panic("mock out the Run method")
//			},
//		}
//
//		// use mockedTransactionChecker in code that requires TransactionChecker
//		// and then make assertions.
//
//	}
type TransactionCheckerMock struct {
	// RunFunc mocks the Run method.
	RunFunc func(ctx context.Context, topic string)

	// calls tracks calls to the methods.
	calls struct {
		// Run holds details about calls to the Run method.
		Run []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Topic is the topic argument value.
			Topic string
		}
	}
	lockRun sync.RWMutex
}

// Run calls RunFunc.
func (mock *TransactionCheckerMock) Run(ctx context.Context, topic string) {
	if mock.RunFunc == nil {
		panic("TransactionCheckerMock.RunFunc: method is nil but TransactionChecker.Run was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Topic string
	}{
		Ctx:   ctx,
		Topic: topic,
	}
	mock.lockRun.Lock()
	mock.calls.Run = append(mock.calls.Run, callInfo)
	mock.lockRun.Unlock()
	mock.RunFunc(ctx, topic)
}

// RunCalls gets all the calls that were made to Run.
// Check the length with:
//
//	len(mockedTransactionChecker.RunCalls())
func (mock *TransactionCheckerMock) RunCalls() []struct {
	Ctx   context.Context
	Topic string
} {
	var calls []struct {
		Ctx   context.Context
		Topic string
	}
	mock.lockRun.RLock()
	calls = mock.calls.Run
	mock.lockRun.RUnlock()
	return calls
}
