// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package invoke

import (
	"context"
	"github.com/Orfeo42/go-redismq/v3/internal/mqtype"
	"sync"
)

// Ensure, that ListenerRegistryMock does implement ListenerRegistry.
// If this is not the case, regenerate this file with moq.
var _ ListenerRegistry = &ListenerRegistryMock{}

// ListenerRegistryMock is a mock implementation of ListenerRegistry.
//
//	func TestSomethingThatUsesListenerRegistry(t *testing.T) {
//
//		// make and configure a mocked ListenerRegistry
//		mockedListenerRegistry := &ListenerRegistryMock{
//			RegisterListenerFunc: func(ctx context.Context, i mqtype.IMessageListener) error {
//				panic("mock out the RegisterListener method")
//			},
//		}
//
//		// use mockedListenerRegistry in code that requires ListenerRegistry
//		// and then make assertions.
//
//	}
type ListenerRegistryMock struct {
	// RegisterListenerFunc mocks the RegisterListener method.
	RegisterListenerFunc func(ctx context.Context, i mqtype.IMessageListener) error

	// calls tracks calls to the methods.
	calls struct {
		// RegisterListener holds details about calls to the RegisterListener method.
		RegisterListener []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// I is the i argument value.
			I mqtype.IMessageListener
		}
	}
	lockRegisterListener sync.RWMutex
}

// RegisterListener calls RegisterListenerFunc.
func (mock *ListenerRegistryMock) RegisterListener(ctx context.Context, i mqtype.IMessageListener) error {
	if mock.RegisterListenerFunc == nil {
		panic("ListenerRegistryMock.RegisterListenerFunc: method is nil but ListenerRegistry.RegisterListener was just called")
	}
	callInfo := struct {
		Ctx context.Context
		I   mqtype.IMessageListener
	}{
		Ctx: ctx,
		I:   i,
	}
	mock.lockRegisterListener.Lock()
	mock.calls.RegisterListener = append(mock.calls.RegisterListener, callInfo)
	mock.lockRegisterListener.Unlock()
	return mock.RegisterListenerFunc(ctx, i)
}

// RegisterListenerCalls gets all the calls that were made to RegisterListener.
// Check the length with:
//
//	len(mockedListenerRegistry.RegisterListenerCalls())
func (mock *ListenerRegistryMock) RegisterListenerCalls() []struct {
	Ctx context.Context
	I   mqtype.IMessageListener
} {
	var calls []struct {
		Ctx context.Context
		I   mqtype.IMessageListener
	}
	mock.lockRegisterListener.RLock()
	calls = mock.calls.RegisterListener
	mock.lockRegisterListener.RUnlock()
	return calls
}
