// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package invoke

import (
	"context"
	"github.com/redis/go-redis/v9"
	"sync"
	"time"
)

// Ensure, that RedisMock does implement Redis.
// If this is not the case, regenerate this file with moq.
var _ Redis = &RedisMock{}

// RedisMock is a mock implementation of Redis.
//
//	func TestSomethingThatUsesRedis(t *testing.T) {
//
//		// make and configure a mocked Redis
//		mockedRedis := &RedisMock{
//			ExpireFunc: func(ctx context.Context, key string, expiration time.Duration) *redis.BoolCmd {
//				panic("mock out the Expire method")
//			},
//			GetFunc: func(ctx context.Context, key string) *redis.StringCmd {
//				panic("mock out the Get method")
//			},
//			PublishFunc: func(ctx context.Context, channel string, message any) *redis.IntCmd {
//				panic("mock out the Publish method")
//			},
//			SetFunc: func(ctx context.Context, key string, value any, expiration time.Duration) *redis.StatusCmd {
//				panic("mock out the Set method")
//			},
//			SubscribeFunc: func(ctx context.Context, channels ...string) *redis.PubSub {
//				panic("mock out the Subscribe method")
//			},
//		}
//
//		// use mockedRedis in code that requires Redis
//		// and then make assertions.
//
//	}
type RedisMock struct {
	// ExpireFunc mocks the Expire method.
	ExpireFunc func(ctx context.Context, key string, expiration time.Duration) *redis.BoolCmd

	// GetFunc mocks the Get method.
	GetFunc func(ctx context.Context, key string) *redis.StringCmd

	// PublishFunc mocks the Publish method.
	PublishFunc func(ctx context.Context, channel string, message any) *redis.IntCmd

	// SetFunc mocks the Set method.
	SetFunc func(ctx context.Context, key string, value any, expiration time.Duration) *redis.StatusCmd

	// SubscribeFunc mocks the Subscribe method.
	SubscribeFunc func(ctx context.Context, channels ...string) *redis.PubSub

	// calls tracks calls to the methods.
	calls struct {
		// Expire holds details about calls to the Expire method.
		Expire []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Key is the key argument value.
			Key string
			// Expiration is the expiration argument value.
			Expiration time.Duration
		}
		// Get holds details about calls to the Get method.
		Get []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Key is the key argument value.
			Key string
		}
		// Publish holds details about calls to the Publish method.
		Publish []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Channel is the channel argument value.
			Channel string
			// Message is the message argument value.
			Message any
		}
		// Set holds details about calls to the Set method.
		Set []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Key is the key argument value.
			Key string
			// Value is the value argument value.
			Value any
			// Expiration is the expiration argument value.
			Expiration time.Duration
		}
		// Subscribe holds details about calls to the Subscribe method.
		Subscribe []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Channels is the channels argument value.
			Channels []string
		}
	}
	lockExpire    sync.RWMutex
	lockGet       sync.RWMutex
	lockPublish   sync.RWMutex
	lockSet       sync.RWMutex
	lockSubscribe sync.RWMutex
}

// Expire calls ExpireFunc.
func (mock *RedisMock) Expire(ctx context.Context, key string, expiration time.Duration) *redis.BoolCmd {
	if mock.ExpireFunc == nil {
		panic("RedisMock.ExpireFunc: method is nil but Redis.Expire was just called")
	}
	callInfo := struct {
		Ctx        context.Context
		Key        string
		Expiration time.Duration
	}{
		Ctx:        ctx,
		Key:        key,
		Expiration: expiration,
	}
	mock.lockExpire.Lock()
	mock.calls.Expire = append(mock.calls.Expire, callInfo)
	mock.lockExpire.Unlock()
	return mock.ExpireFunc(ctx, key, expiration)
}

// ExpireCalls gets all the calls that were made to Expire.
// Check the length with:
//
//	len(mockedRedis.ExpireCalls())
func (mock *RedisMock) ExpireCalls() []struct {
	Ctx        context.Context
	Key        string
	Expiration time.Duration
} {
	var calls []struct {
		Ctx        context.Context
		Key        string
		Expiration time.Duration
	}
	mock.lockExpire.RLock()
	calls = mock.calls.Expire
	mock.lockExpire.RUnlock()
	return calls
}

// Get calls GetFunc.
func (mock *RedisMock) Get(ctx context.Context, key string) *redis.StringCmd {
	if mock.GetFunc == nil {
		panic("RedisMock.GetFunc: method is nil but Redis.Get was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Key string
	}{
		Ctx: ctx,
		Key: key,
	}
	mock.lockGet.Lock()
	mock.calls.Get = append(mock.calls.Get, callInfo)
	mock.lockGet.Unlock()
	return mock.GetFunc(ctx, key)
}

// GetCalls gets all the calls that were made to Get.
// Check the length with:
//
//	len(mockedRedis.GetCalls())
func (mock *RedisMock) GetCalls() []struct {
	Ctx context.Context
	Key string
} {
	var calls []struct {
		Ctx context.Context
		Key string
	}
	mock.lockGet.RLock()
	calls = mock.calls.Get
	mock.lockGet.RUnlock()
	return calls
}

// Publish calls PublishFunc.
func (mock *RedisMock) Publish(ctx context.Context, channel string, message any) *redis.IntCmd {
	if mock.PublishFunc == nil {
		panic("RedisMock.PublishFunc: method is nil but Redis.Publish was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		Channel string
		Message any
	}{
		Ctx:     ctx,
		Channel: channel,
		Message: message,
	}
	mock.lockPublish.Lock()
	mock.calls.Publish = append(mock.calls.Publish, callInfo)
	mock.lockPublish.Unlock()
	return mock.PublishFunc(ctx, channel, message)
}

// PublishCalls gets all the calls that were made to Publish.
// Check the length with:
//
//	len(mockedRedis.PublishCalls())
func (mock *RedisMock) PublishCalls() []struct {
	Ctx     context.Context
	Channel string
	Message any
} {
	var calls []struct {
		Ctx     context.Context
		Channel string
		Message any
	}
	mock.lockPublish.RLock()
	calls = mock.calls.Publish
	mock.lockPublish.RUnlock()
	return calls
}

// Set calls SetFunc.
func (mock *RedisMock) Set(ctx context.Context, key string, value any, expiration time.Duration) *redis.StatusCmd {
	if mock.SetFunc == nil {
		panic("RedisMock.SetFunc: method is nil but Redis.Set was just called")
	}
	callInfo := struct {
		Ctx        context.Context
		Key        string
		Value      any
		Expiration time.Duration
	}{
		Ctx:        ctx,
		Key:        key,
		Value:      value,
		Expiration: expiration,
	}
	mock.lockSet.Lock()
	mock.calls.Set = append(mock.calls.Set, callInfo)
	mock.lockSet.Unlock()
	return mock.SetFunc(ctx, key, value, expiration)
}

// SetCalls gets all the calls that were made to Set.
// Check the length with:
//
//	len(mockedRedis.SetCalls())
func (mock *RedisMock) SetCalls() []struct {
	Ctx        context.Context
	Key        string
	Value      any
	Expiration time.Duration
} {
	var calls []struct {
		Ctx        context.Context
		Key        string
		Value      any
		Expiration time.Duration
	}
	mock.lockSet.RLock()
	calls = mock.calls.Set
	mock.lockSet.RUnlock()
	return calls
}

// Subscribe calls SubscribeFunc.
func (mock *RedisMock) Subscribe(ctx context.Context, channels ...string) *redis.PubSub {
	if mock.SubscribeFunc == nil {
		panic("RedisMock.SubscribeFunc: method is nil but Redis.Subscribe was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		Channels []string
	}{
		Ctx:      ctx,
		Channels: channels,
	}
	mock.lockSubscribe.Lock()
	mock.calls.Subscribe = append(mock.calls.Subscribe, callInfo)
	mock.lockSubscribe.Unlock()
	return mock.SubscribeFunc(ctx, channels...)
}

// SubscribeCalls gets all the calls that were made to Subscribe.
// Check the length with:
//
//	len(mockedRedis.SubscribeCalls())
func (mock *RedisMock) SubscribeCalls() []struct {
	Ctx      context.Context
	Channels []string
} {
	var calls []struct {
		Ctx      context.Context
		Channels []string
	}
	mock.lockSubscribe.RLock()
	calls = mock.calls.Subscribe
	mock.lockSubscribe.RUnlock()
	return calls
}
