// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package txchecker

import (
	"github.com/Orfeo42/go-redismq/v3/internal/mqtype"
	"sync"
)

// Ensure, that CheckerRegistryMock does implement CheckerRegistry.
// If this is not the case, regenerate this file with moq.
var _ CheckerRegistry = &CheckerRegistryMock{}

// CheckerRegistryMock is a mock implementation of CheckerRegistry.
//
//	func TestSomethingThatUsesCheckerRegistry(t *testing.T) {
//
//		// make and configure a mocked CheckerRegistry
//		mockedCheckerRegistry := &CheckerRegistryMock{
//			GetCheckerForFunc: func(topic string, tag string) mqtype.IMessageChecker {
//				panic("mock out the GetCheckerFor method")
//			},
//		}
//
//		// use mockedCheckerRegistry in code that requires CheckerRegistry
//		// and then make assertions.
//
//	}
type CheckerRegistryMock struct {
	// GetCheckerForFunc mocks the GetCheckerFor method.
	GetCheckerForFunc func(topic string, tag string) mqtype.IMessageChecker

	// calls tracks calls to the methods.
	calls struct {
		// GetCheckerFor holds details about calls to the GetCheckerFor method.
		GetCheckerFor []struct {
			// Topic is the topic argument value.
			Topic string
			// Tag is the tag argument value.
			Tag string
		}
	}
	lockGetCheckerFor sync.RWMutex
}

// GetCheckerFor calls GetCheckerForFunc.
func (mock *CheckerRegistryMock) GetCheckerFor(topic string, tag string) mqtype.IMessageChecker {
	if mock.GetCheckerForFunc == nil {
		panic("CheckerRegistryMock.GetCheckerForFunc: method is nil but CheckerRegistry.GetCheckerFor was just called")
	}
	callInfo := struct {
		Topic string
		Tag   string
	}{
		Topic: topic,
		Tag:   tag,
	}
	mock.lockGetCheckerFor.Lock()
	mock.calls.GetCheckerFor = append(mock.calls.GetCheckerFor, callInfo)
	mock.lockGetCheckerFor.Unlock()
	return mock.GetCheckerForFunc(topic, tag)
}

// GetCheckerForCalls gets all the calls that were made to GetCheckerFor.
// Check the length with:
//
//	len(mockedCheckerRegistry.GetCheckerForCalls())
func (mock *CheckerRegistryMock) GetCheckerForCalls() []struct {
	Topic string
	Tag   string
} {
	var calls []struct {
		Topic string
		Tag   string
	}
	mock.lockGetCheckerFor.RLock()
	calls = mock.calls.GetCheckerFor
	mock.lockGetCheckerFor.RUnlock()
	return calls
}
