// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package txchecker

import (
	"context"
	"github.com/Orfeo42/go-redismq/v3/internal/mqtype"
	"sync"
)

// Ensure, that TransactionCompleterMock does implement TransactionCompleter.
// If this is not the case, regenerate this file with moq.
var _ TransactionCompleter = &TransactionCompleterMock{}

// TransactionCompleterMock is a mock implementation of TransactionCompleter.
//
//	func TestSomethingThatUsesTransactionCompleter(t *testing.T) {
//
//		// make and configure a mocked TransactionCompleter
//		mockedTransactionCompleter := &TransactionCompleterMock{
//			CommitFunc: func(ctx context.Context, message *mqtype.Message) (bool, error) {
//				panic("mock out the Commit method")
//			},
//			RollbackFunc: func(ctx context.Context, message *mqtype.Message) (bool, error) {
//				panic("mock out the Rollback method")
//			},
//		}
//
//		// use mockedTransactionCompleter in code that requires TransactionCompleter
//		// and then make assertions.
//
//	}
type TransactionCompleterMock struct {
	// CommitFunc mocks the Commit method.
	CommitFunc func(ctx context.Context, message *mqtype.Message) (bool, error)

	// RollbackFunc mocks the Rollback method.
	RollbackFunc func(ctx context.Context, message *mqtype.Message) (bool, error)

	// calls tracks calls to the methods.
	calls struct {
		// Commit holds details about calls to the Commit method.
		Commit []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Message is the message argument value.
			Message *mqtype.Message
		}
		// Rollback holds details about calls to the Rollback method.
		Rollback []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Message is the message argument value.
			Message *mqtype.Message
		}
	}
	lockCommit   sync.RWMutex
	lockRollback sync.RWMutex
}

// Commit calls CommitFunc.
func (mock *TransactionCompleterMock) Commit(ctx context.Context, message *mqtype.Message) (bool, error) {
	if mock.CommitFunc == nil {
		panic("TransactionCompleterMock.CommitFunc: method is nil but TransactionCompleter.Commit was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		Message *mqtype.Message
	}{
		Ctx:     ctx,
		Message: message,
	}
	mock.lockCommit.Lock()
	mock.calls.Commit = append(mock.calls.Commit, callInfo)
	mock.lockCommit.Unlock()
	return mock.CommitFunc(ctx, message)
}

// CommitCalls gets all the calls that were made to Commit.
// Check the length with:
//
//	len(mockedTransactionCompleter.CommitCalls())
func (mock *TransactionCompleterMock) CommitCalls() []struct {
	Ctx     context.Context
	Message *mqtype.Message
} {
	var calls []struct {
		Ctx     context.Context
		Message *mqtype.Message
	}
	mock.lockCommit.RLock()
	calls = mock.calls.Commit
	mock.lockCommit.RUnlock()
	return calls
}

// Rollback calls RollbackFunc.
func (mock *TransactionCompleterMock) Rollback(ctx context.Context, message *mqtype.Message) (bool, error) {
	if mock.RollbackFunc == nil {
		panic("TransactionCompleterMock.RollbackFunc: method is nil but TransactionCompleter.Rollback was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		Message *mqtype.Message
	}{
		Ctx:     ctx,
		Message: message,
	}
	mock.lockRollback.Lock()
	mock.calls.Rollback = append(mock.calls.Rollback, callInfo)
	mock.lockRollback.Unlock()
	return mock.RollbackFunc(ctx, message)
}

// RollbackCalls gets all the calls that were made to Rollback.
// Check the length with:
//
//	len(mockedTransactionCompleter.RollbackCalls())
func (mock *TransactionCompleterMock) RollbackCalls() []struct {
	Ctx     context.Context
	Message *mqtype.Message
} {
	var calls []struct {
		Ctx     context.Context
		Message *mqtype.Message
	}
	mock.lockRollback.RLock()
	calls = mock.calls.Rollback
	mock.lockRollback.RUnlock()
	return calls
}
