// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package txchecker

import (
	"context"
	"github.com/redis/go-redis/v9"
	"sync"
)

// Ensure, that RedisMock does implement Redis.
// If this is not the case, regenerate this file with moq.
var _ Redis = &RedisMock{}

// RedisMock is a mock implementation of Redis.
//
//	func TestSomethingThatUsesRedis(t *testing.T) {
//
//		// make and configure a mocked Redis
//		mockedRedis := &RedisMock{
//			GetFunc: func(ctx context.Context, key string) *redis.StringCmd {
//				panic("mock out the Get method")
//			},
//			LRangeFunc: func(ctx context.Context, key string, start int64, stop int64) *redis.StringSliceCmd {
//				panic("mock out the LRange method")
//			},
//			TxPipelinedFunc: func(ctx context.Context, fn func(redis.Pipeliner) error) ([]redis.Cmder, error) {
//				panic("mock out the TxPipelined method")
//			},
//		}
//
//		// use mockedRedis in code that requires Redis
//		// and then make assertions.
//
//	}
type RedisMock struct {
	// GetFunc mocks the Get method.
	GetFunc func(ctx context.Context, key string) *redis.StringCmd

	// LRangeFunc mocks the LRange method.
	LRangeFunc func(ctx context.Context, key string, start int64, stop int64) *redis.StringSliceCmd

	// TxPipelinedFunc mocks the TxPipelined method.
	TxPipelinedFunc func(ctx context.Context, fn func(redis.Pipeliner) error) ([]redis.Cmder, error)

	// calls tracks calls to the methods.
	calls struct {
		// Get holds details about calls to the Get method.
		Get []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Key is the key argument value.
			Key string
		}
		// LRange holds details about calls to the LRange method.
		LRange []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Key is the key argument value.
			Key string
			// Start is the start argument value.
			Start int64
			// Stop is the stop argument value.
			Stop int64
		}
		// TxPipelined holds details about calls to the TxPipelined method.
		TxPipelined []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Fn is the fn argument value.
			Fn func(redis.Pipeliner) error
		}
	}
	lockGet         sync.RWMutex
	lockLRange      sync.RWMutex
	lockTxPipelined sync.RWMutex
}

// Get calls GetFunc.
func (mock *RedisMock) Get(ctx context.Context, key string) *redis.StringCmd {
	if mock.GetFunc == nil {
		panic("RedisMock.GetFunc: method is nil but Redis.Get was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Key string
	}{
		Ctx: ctx,
		Key: key,
	}
	mock.lockGet.Lock()
	mock.calls.Get = append(mock.calls.Get, callInfo)
	mock.lockGet.Unlock()
	return mock.GetFunc(ctx, key)
}

// GetCalls gets all the calls that were made to Get.
// Check the length with:
//
//	len(mockedRedis.GetCalls())
func (mock *RedisMock) GetCalls() []struct {
	Ctx context.Context
	Key string
} {
	var calls []struct {
		Ctx context.Context
		Key string
	}
	mock.lockGet.RLock()
	calls = mock.calls.Get
	mock.lockGet.RUnlock()
	return calls
}

// LRange calls LRangeFunc.
func (mock *RedisMock) LRange(ctx context.Context, key string, start int64, stop int64) *redis.StringSliceCmd {
	if mock.LRangeFunc == nil {
		panic("RedisMock.LRangeFunc: method is nil but Redis.LRange was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Key   string
		Start int64
		Stop  int64
	}{
		Ctx:   ctx,
		Key:   key,
		Start: start,
		Stop:  stop,
	}
	mock.lockLRange.Lock()
	mock.calls.LRange = append(mock.calls.LRange, callInfo)
	mock.lockLRange.Unlock()
	return mock.LRangeFunc(ctx, key, start, stop)
}

// LRangeCalls gets all the calls that were made to LRange.
// Check the length with:
//
//	len(mockedRedis.LRangeCalls())
func (mock *RedisMock) LRangeCalls() []struct {
	Ctx   context.Context
	Key   string
	Start int64
	Stop  int64
} {
	var calls []struct {
		Ctx   context.Context
		Key   string
		Start int64
		Stop  int64
	}
	mock.lockLRange.RLock()
	calls = mock.calls.LRange
	mock.lockLRange.RUnlock()
	return calls
}

// TxPipelined calls TxPipelinedFunc.
func (mock *RedisMock) TxPipelined(ctx context.Context, fn func(redis.Pipeliner) error) ([]redis.Cmder, error) {
	if mock.TxPipelinedFunc == nil {
		panic("RedisMock.TxPipelinedFunc: method is nil but Redis.TxPipelined was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Fn  func(redis.Pipeliner) error
	}{
		Ctx: ctx,
		Fn:  fn,
	}
	mock.lockTxPipelined.Lock()
	mock.calls.TxPipelined = append(mock.calls.TxPipelined, callInfo)
	mock.lockTxPipelined.Unlock()
	return mock.TxPipelinedFunc(ctx, fn)
}

// TxPipelinedCalls gets all the calls that were made to TxPipelined.
// Check the length with:
//
//	len(mockedRedis.TxPipelinedCalls())
func (mock *RedisMock) TxPipelinedCalls() []struct {
	Ctx context.Context
	Fn  func(redis.Pipeliner) error
} {
	var calls []struct {
		Ctx context.Context
		Fn  func(redis.Pipeliner) error
	}
	mock.lockTxPipelined.RLock()
	calls = mock.calls.TxPipelined
	mock.lockTxPipelined.RUnlock()
	return calls
}
