// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package txchecker

import (
	"context"
	"github.com/Orfeo42/go-redismq/v3/internal/mqtype"
	"sync"
)

// Ensure, that TracerMock does implement Tracer.
// If this is not the case, regenerate this file with moq.
var _ Tracer = &TracerMock{}

// TracerMock is a mock implementation of Tracer.
//
//	func TestSomethingThatUsesTracer(t *testing.T) {
//
//		// make and configure a mocked Tracer
//		mockedTracer := &TracerMock{
//			ConsumeContextFunc: func(ctx context.Context, message *mqtype.Message) context.Context {
//				panic("mock out the ConsumeContext method")
//			},
//		}
//
//		// use mockedTracer in code that requires Tracer
//		// and then make assertions.
//
//	}
type TracerMock struct {
	// ConsumeContextFunc mocks the ConsumeContext method.
	ConsumeContextFunc func(ctx context.Context, message *mqtype.Message) context.Context

	// calls tracks calls to the methods.
	calls struct {
		// ConsumeContext holds details about calls to the ConsumeContext method.
		ConsumeContext []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Message is the message argument value.
			Message *mqtype.Message
		}
	}
	lockConsumeContext sync.RWMutex
}

// ConsumeContext calls ConsumeContextFunc.
func (mock *TracerMock) ConsumeContext(ctx context.Context, message *mqtype.Message) context.Context {
	if mock.ConsumeContextFunc == nil {
		panic("TracerMock.ConsumeContextFunc: method is nil but Tracer.ConsumeContext was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		Message *mqtype.Message
	}{
		Ctx:     ctx,
		Message: message,
	}
	mock.lockConsumeContext.Lock()
	mock.calls.ConsumeContext = append(mock.calls.ConsumeContext, callInfo)
	mock.lockConsumeContext.Unlock()
	return mock.ConsumeContextFunc(ctx, message)
}

// ConsumeContextCalls gets all the calls that were made to ConsumeContext.
// Check the length with:
//
//	len(mockedTracer.ConsumeContextCalls())
func (mock *TracerMock) ConsumeContextCalls() []struct {
	Ctx     context.Context
	Message *mqtype.Message
} {
	var calls []struct {
		Ctx     context.Context
		Message *mqtype.Message
	}
	mock.lockConsumeContext.RLock()
	calls = mock.calls.ConsumeContext
	mock.lockConsumeContext.RUnlock()
	return calls
}
